# Use faster LXD containers
arch: arm64-graviton2
virt: lxd
os: linux
dist: focal
group: edge

language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy3"

matrix:
  fast_finish: true
  allow_failures:
    - python: '3.9-dev'

install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r test-requirements.txt
  - python setup.py --version

# Run test
script:
  - pytest -vv
